---
# Provision a CentOS 9 host for Ansible

- name: Find out the Ethernet Interface
  ansible.builtin.shell:
    cmd: "nmcli -t device | grep ethernet:connected | cut -d ':' -f 1 -"
    register: iface

- name: Add an Ethernet connection with static IP configuration
    community.general.nmcli:
      conn_name: "{{ iface }}"
      ifname: "{{ iface }}"
      type: ethernet
      ip4: "{{ ip_subnet }}"
      gw4: "{{ gateway }}"
      dns4:
        - 172.22.110.10
        - 172.24.110.10
      dns4_search:
        - calgarycoop.com
      state: present
